//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cause
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cause()
        {
            this.Signature = new HashSet<Signature>();
        }
    
        public int CauseID { get; set; }
        public string Category { get; set; }
        public string ExplaineIssue { get; set; }
        public byte[] Image { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signature> Signature { get; set; }
    }
}
