//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signature
    {
        public int SignatureID { get; set; }
        public int CauseID { get; set; }
        public int UserID { get; set; }
        public string Username { get; set; }
    
        public virtual Cause Cause { get; set; }
        public virtual User User { get; set; }
    }
}
